# For running server in info mode ('info' command)
port: 4040
disableHttps: true

# Blockchain configuration
baseChain:
    chainId: 84532
    networkUrl: 'https://mainnet.base.org'
    blockTimeMs: 2000
riverChain:
    chainId: 550
    networkUrl: 'https://mainnet.rpc.river.build'
    blockTimeMs: 2000

# Base contracts TODO: not set yet
architectContract:
    address: '0x9978c826d93883701522d2CA645d5436e5654252'

# River contracts
registryContract:
    address: '0x1298c03Fde548dc433a452573E36A713b38A0404'

# Disable logging
log:
    file: ''
    level: info
    console: true
    noColor: false
    format: text
