# Blockchain configuration
baseChain:
    chainId: 8453
    networkUrl: 'https://mainnet.base.org'
    blockTimeMs: 2000
riverChain:
    chainId: 550
    networkUrl: 'https://mainnet.rpc.river.build'
    blockTimeMs: 2000

# Base contracts TODO: not set yet
architectContract:
    address: '0x9978c826d93883701522d2CA645d5436e5654252'

# River contracts
registryContract:
    address: '0x1298c03Fde548dc433a452573E36A713b38A0404'
